openapi: 3.0.0
info:
  title: MERS API
  version: 1.0.0
  license:
    name: MIT
servers:
- url: http://localhost:3000/v1
paths:
  /images:
    get:
      summary: Get display single image
      operationId: getImages
      tags:
        - images
      parameters:
        - name: id
          in: path 
          required: true
          schema:
            type: integer
            format: uint64
      responses:
        '200':
          description: Successful acquisition of display single image
          content:
              application/json:    
                schema:
                  $ref: "#/components/schemas/Image"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /movies:
    get:
      summary: get a display movie
      tags:
        - movies
      operationId: getMovie
      parameters:
      - name: id
        in: path
        description: Movie ID
        required: true
        schema:
          type: integer
          format: uint32
      responses:
        "200":
          description: URL for Movie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /targets:
    get:
      summary: get some rated targets
      tags:
      - targets
      operationId: getTargets
      parameters:
      - name: type
        in: path
        description: media type
        required: true
        schema:
          type: string
          example:
          - image
          - movie
      - name: num
        in: path
        description: how many rated targets to get
        required: true
        schema:
          type: integer
          format: uint32
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Targets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /trials:
    post:
      summary: create a trial result
      description: create a trial result containing a set of a subject info and rating results
      requestBody:
        description: trial result
        required: true
        $ref: '#/components/requestBodies/Trial'
      responses:
        '201':
          description: successful to create a trial result
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  requestBodies:
    Trial:
      content:
        application/json:
          schema:
            type: object
            properties:
              datetime:
                type: string
                format: date-time
              subject:
                type: object
                properties:
                  participant_id:
                    type: integer
                    format: uint64
                  age:
                    type: integer
                    format: uint64
                  gender:
                    type: string
                  handedness:
                    type: string
                  vision:
                    type: string
                  vision_Aid:
                    type: string
                  education:
                    type: string
                  alcohol_consumption:
                    type: string
                  coffee_consumption:
                    type: string
                  tea_consumption:
                    type: string
                  tobacco_consumption:
                    type: string
                  drug_consumption:
                    type: string
                  syndroms:
                    type: string
                  hours_of_sleep_last_night:
                    type: number
                    format: float
                  normal_hours_of_sleep:
                    type: number
                    format: float
                  level_of_Alertness:
                    type: string
                  distribute_physiological_recordings:
                    type: boolean
                  publish_audio_visual_recordings:
                    type: boolean
                  head_circumference:
                    type: number
                    format: float
                  distance_nasion-Inion:
                    type: number
                    format: float
                  distance_left-right_jaw_hinge:
                    type: number
                    format: float
              ratings:
                type: array
                items:
                  type: object
                  properties:
                    media_id:
                      type: integer
                      format: uint32
                    emotions:
                      type: object
                      properties:
                        valence:
                          type: number
                          format: float
                        arousal:
                          type: number
                          format: float
                        liking:
                          type: number
                          format: float
                        dominance:
                          type: number
                          format: float
                        famility:
                          type: number
                          format: float
            required:
              - date
              - subject
              - ratings
  schemas:
    Image:
      type: object
      properties:
        media_id:
          type: integer
          format: uint64
        type: 
          type: string
        filename:
          type: string
        rating_times:
          type: integer
          format: int64
    Movie:
      type: object
      properties:
        id:
          type: integer
          format: uint32
        url:
          type: string
      required:
        - id
        - url
    Targets:
      type: array
      items: 
        type: object
        properties:
          type: 
            type: string
          ids:
            type: array
            items:
              type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
      - code
      - message
